# Generated by Django 3.2.9 on 2021-11-19 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211119_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_by',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='suivi par'),
        ),
    ]
